package Vista;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class Card_Area extends PanelRedondeado {

    private Color color1Temp, color2Temp;

    String path = "";
    String textArea = "";
    String textTitle = "";
    Color backgroundColor = new Color(243, 243, 243);
    Color backgroundColorHover = new Color(230, 230, 230);

    private Color color1, color2;

    public Color getColor1() {
        return color1;
    }

    public void setColor1(Color color1) {
        this.color1 = color1;
        repaint();
    }

    public Color getColor2() {
        return color2;
    }

    public void setColor2(Color color2) {
        this.color2 = color2;
        repaint();
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
        Icon.setPath(path);
    }

    public String getTextArea() {
        return textArea;
    }

    public void setTextArea(String textArea) {
        this.textArea = textArea;
        lbArea.setText(textArea);
    }

    public String getTextTitle() {
        return textTitle;
    }

    public void setTextTitle(String textTitle) {
        this.textTitle = textTitle;
        lbTitle.setText(textTitle);
    }

    public Card_Area() {
        initComponents();
        setOpaque(false);

        color1 = Color.BLACK;
        color2 = Color.WHITE;
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {

                color1Temp = color1;
                color2Temp = color2;

                setColor1(backgroundColorHover);
                setColor2(backgroundColorHover.darker());
            }

            @Override
            public void mouseExited(MouseEvent e) {
                if (color1Temp != null) {
                    setColor1(color1Temp);
                }
                if (color2Temp != null) {
                    setColor2(color2Temp);
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbArea = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        Icon = new Vista.ImagenAdaptable();

        lbArea.setFont(new java.awt.Font("Julius Sans One", 0, 14)); // NOI18N
        lbArea.setText("Area");

        lbTitle.setFont(new java.awt.Font("Julius Sans One", 0, 14)); // NOI18N
        lbTitle.setText("Title");

        Icon.setPath("/Recursos/usuario.png");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lbTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbArea)
                            .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTitle)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics gr) {
        super.paintComponent(gr);

        Graphics2D g2 = (Graphics2D) gr.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, color1, 0, getHeight(), color2);
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);

        // Configuración de color blanco con transparencia (Alpha = 50) para los círculos
        g2.setColor(new Color(255, 255, 255, 50));

        // Dibujo de los círculos decorativos en la parte derecha
        g2.fillOval(getWidth() - (getHeight() / 2), 10, getHeight(), getHeight());
        g2.fillOval(getWidth() - (getHeight() / 2) - 20, getHeight() / 2 + 20, getHeight(), getHeight());

        // Liberar los recursos gráficos creados
        g2.dispose();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.ImagenAdaptable Icon;
    private javax.swing.JLabel lbArea;
    private javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables
}
