package Vista;

public class frmHome extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmHome.class.getName());

    public frmHome() {
        initComponents();

        // Forzamos a CardLayout a mostrar "inicio" al arrancar
        java.awt.CardLayout card = (java.awt.CardLayout) Main.getLayout();
        card.show(Main, "inicio");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        Lista = new javax.swing.JPanel();
        btnInicio = new Vista.Lista();
        btnSistema = new Vista.Lista();
        btnManto = new Vista.Lista();
        btnConsulta = new Vista.Lista();
        imagenAdaptable1 = new Vista.ImagenAdaptable();
        Main = new javax.swing.JPanel();
        JPInicio = new javax.swing.JPanel();
        imagenAdaptable2 = new Vista.ImagenAdaptable();
        JPSistema = new javax.swing.JPanel();
        cardUsuario = new Vista.Card_Area();
        cardRol = new Vista.Card_Area();
        cardCliente = new Vista.Card_Area();
        cardProveedor = new Vista.Card_Area();
        JPMante = new javax.swing.JPanel();
        cardProducto = new Vista.Card_Area();
        cardCategoria = new Vista.Card_Area();
        cardAlmacen = new Vista.Card_Area();
        cardMarca = new Vista.Card_Area();
        JPConsulta = new javax.swing.JPanel();
        cardMovimiento = new Vista.Card_Area();
        cardDetalle = new Vista.Card_Area();
        cardInventario = new Vista.Card_Area();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SenaTechPro - Inventario");
        setResizable(false);

        Sidebar.setBackground(new java.awt.Color(255, 255, 255));

        Lista.setBackground(new java.awt.Color(255, 255, 255));
        Lista.setLayout(new java.awt.GridLayout(0, 1, 0, 8));

        btnInicio.setPath("/Recursos/inicio.png");
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        Lista.add(btnInicio);

        btnSistema.setPath("/Recursos/sistema.png");
        btnSistema.setText("SISTEMA");
        btnSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSistemaMouseClicked(evt);
            }
        });
        Lista.add(btnSistema);

        btnManto.setPath("/Recursos/mante.png");
        btnManto.setText("MANTENIMIENTO");
        btnManto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMantoMouseClicked(evt);
            }
        });
        Lista.add(btnManto);

        btnConsulta.setPath("/Recursos/consulta.png");
        btnConsulta.setText("CONSULTA");
        btnConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultaMouseClicked(evt);
            }
        });
        Lista.add(btnConsulta);

        imagenAdaptable1.setPath("/Recursos/logo.png");

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenAdaptable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenAdaptable1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        Main.setLayout(new java.awt.CardLayout());

        imagenAdaptable2.setPath("/Recursos/fondo.png");

        javax.swing.GroupLayout JPInicioLayout = new javax.swing.GroupLayout(JPInicio);
        JPInicio.setLayout(JPInicioLayout);
        JPInicioLayout.setHorizontalGroup(
            JPInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenAdaptable2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPInicioLayout.setVerticalGroup(
            JPInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenAdaptable2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Main.add(JPInicio, "inicio");

        cardUsuario.setColor1(new java.awt.Color(225, 230, 235));
        cardUsuario.setColor2(new java.awt.Color(150, 190, 240));
        cardUsuario.setTextArea("Sistema");
        cardUsuario.setTextTitle("Usuario");

        cardRol.setColor1(new java.awt.Color(225, 230, 235));
        cardRol.setColor2(new java.awt.Color(150, 190, 240));
        cardRol.setPath("/Recursos/rol.png");
        cardRol.setTextArea("Sistema");
        cardRol.setTextTitle("Rol");

        cardCliente.setColor1(new java.awt.Color(225, 230, 235));
        cardCliente.setColor2(new java.awt.Color(150, 190, 240));
        cardCliente.setPath("/Recursos/cliente.png");
        cardCliente.setTextArea("Sistema");
        cardCliente.setTextTitle("Cliente");

        cardProveedor.setColor1(new java.awt.Color(225, 230, 235));
        cardProveedor.setColor2(new java.awt.Color(150, 190, 240));
        cardProveedor.setPath("/Recursos/proveedor.png");
        cardProveedor.setTextArea("Sistema");
        cardProveedor.setTextTitle("Proveedor");

        javax.swing.GroupLayout JPSistemaLayout = new javax.swing.GroupLayout(JPSistema);
        JPSistema.setLayout(JPSistemaLayout);
        JPSistemaLayout.setHorizontalGroup(
            JPSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSistemaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(JPSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(cardCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(JPSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardRol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        JPSistemaLayout.setVerticalGroup(
            JPSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSistemaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(JPSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(JPSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        Main.add(JPSistema, "sistema");

        cardProducto.setColor1(new java.awt.Color(190, 245, 220));
        cardProducto.setColor2(new java.awt.Color(150, 190, 240));
        cardProducto.setPath("/Recursos/producto.png");
        cardProducto.setTextArea("Mantenimiento");
        cardProducto.setTextTitle("Producto");
        cardProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardProductoMouseClicked(evt);
            }
        });

        cardCategoria.setColor1(new java.awt.Color(190, 245, 220));
        cardCategoria.setColor2(new java.awt.Color(150, 190, 240));
        cardCategoria.setPath("/Recursos/categoria.png");
        cardCategoria.setTextArea("Mantenimiento");
        cardCategoria.setTextTitle("Categoria");

        cardAlmacen.setColor1(new java.awt.Color(190, 245, 220));
        cardAlmacen.setColor2(new java.awt.Color(150, 190, 240));
        cardAlmacen.setPath("/Recursos/almacen.png");
        cardAlmacen.setTextArea("Mantenimiento");
        cardAlmacen.setTextTitle("Almacen");

        cardMarca.setColor1(new java.awt.Color(190, 245, 220));
        cardMarca.setColor2(new java.awt.Color(150, 190, 240));
        cardMarca.setPath("/Recursos/marca.png");
        cardMarca.setTextArea("Mantenimiento");
        cardMarca.setTextTitle("Marca");

        javax.swing.GroupLayout JPManteLayout = new javax.swing.GroupLayout(JPMante);
        JPMante.setLayout(JPManteLayout);
        JPManteLayout.setHorizontalGroup(
            JPManteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPManteLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(JPManteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(cardAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(JPManteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        JPManteLayout.setVerticalGroup(
            JPManteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPManteLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(JPManteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(JPManteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        Main.add(JPMante, "mante");

        cardMovimiento.setColor1(new java.awt.Color(255, 220, 200));
        cardMovimiento.setColor2(new java.awt.Color(150, 190, 240));
        cardMovimiento.setPath("/Recursos/movimiento.png");
        cardMovimiento.setTextArea("Consulta");
        cardMovimiento.setTextTitle("Movimiento");

        cardDetalle.setColor1(new java.awt.Color(255, 220, 200));
        cardDetalle.setColor2(new java.awt.Color(150, 190, 240));
        cardDetalle.setPath("/Recursos/detalle.png");
        cardDetalle.setTextArea("Consulta");
        cardDetalle.setTextTitle("Detalle");

        cardInventario.setColor1(new java.awt.Color(255, 220, 200));
        cardInventario.setColor2(new java.awt.Color(150, 190, 240));
        cardInventario.setPath("/Recursos/inventario.png");
        cardInventario.setTextArea("Consulta");
        cardInventario.setTextTitle("Inventario");

        javax.swing.GroupLayout JPConsultaLayout = new javax.swing.GroupLayout(JPConsulta);
        JPConsulta.setLayout(JPConsultaLayout);
        JPConsultaLayout.setHorizontalGroup(
            JPConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPConsultaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(JPConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(cardDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        JPConsultaLayout.setVerticalGroup(
            JPConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPConsultaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(JPConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(cardInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Main.add(JPConsulta, "consulta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout card = (java.awt.CardLayout) Main.getLayout();
        card.show(Main, "inicio");

    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnMantoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMantoMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout card = (java.awt.CardLayout) Main.getLayout();
        card.show(Main, "mante");
    }//GEN-LAST:event_btnMantoMouseClicked

    private void btnSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSistemaMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout card = (java.awt.CardLayout) Main.getLayout();
        card.show(Main, "sistema");
    }//GEN-LAST:event_btnSistemaMouseClicked

    private void btnConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaMouseClicked
        // TODO add your handling code here:
        java.awt.CardLayout card = (java.awt.CardLayout) Main.getLayout();
        card.show(Main, "consulta");
    }//GEN-LAST:event_btnConsultaMouseClicked

    private void cardProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardProductoMouseClicked
        // TODO add your handling code here:
        this.setVisible(true);
        frmProducto pro = new frmProducto();
        pro.setVisible(true);
    }//GEN-LAST:event_cardProductoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmHome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPConsulta;
    private javax.swing.JPanel JPInicio;
    private javax.swing.JPanel JPMante;
    private javax.swing.JPanel JPSistema;
    private javax.swing.JPanel Lista;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Sidebar;
    private Vista.Lista btnConsulta;
    private Vista.Lista btnInicio;
    private Vista.Lista btnManto;
    private Vista.Lista btnSistema;
    private Vista.Card_Area cardAlmacen;
    private Vista.Card_Area cardCategoria;
    private Vista.Card_Area cardCliente;
    private Vista.Card_Area cardDetalle;
    private Vista.Card_Area cardInventario;
    private Vista.Card_Area cardMarca;
    private Vista.Card_Area cardMovimiento;
    private Vista.Card_Area cardProducto;
    private Vista.Card_Area cardProveedor;
    private Vista.Card_Area cardRol;
    private Vista.Card_Area cardUsuario;
    private Vista.ImagenAdaptable imagenAdaptable1;
    private Vista.ImagenAdaptable imagenAdaptable2;
    // End of variables declaration//GEN-END:variables
}
