/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class frmPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipal.class.getName());

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        
        jPanelSistema.setVisible(false);
        jPanelMantenimiento.setVisible(false);
        jPanelInicio.setVisible(true);
        jPanelConsultas.setVisible(false);

        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/Recursos/logo.png"));
        Icon icon = new ImageIcon(imageIcon.getImage().getScaledInstance(350, 220, Image.SCALE_DEFAULT));
        jLogo.setIcon(icon);

        jPanelInicio.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ajustarImagen();
            }
        });
        
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            ajustarImagen();
        }
    });

    }

    private void ajustarImagen() {
        ImageIcon imageIcon2 = new ImageIcon(getClass().getResource("/Recursos/fondo.png"));

        Image imagenEscalada = imageIcon2.getImage().getScaledInstance(
                jPanelInicio.getWidth(),
                jPanelInicio.getHeight(),
                Image.SCALE_FAST
        );

        jFondo.setIcon(new ImageIcon(imagenEscalada));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        jLogo = new javax.swing.JLabel();
        btnSistema = new javax.swing.JButton();
        btnMantenimiento = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        jPanelContent = new javax.swing.JPanel();
        jPanelConsultas = new javax.swing.JPanel();
        jPanelContentRegresar1 = new javax.swing.JPanel();
        jRegresarM1 = new javax.swing.JButton();
        jPanelContentOpciones1 = new javax.swing.JPanel();
        jPanelContenMovimiento = new javax.swing.JPanel();
        btnMovimiento = new javax.swing.JButton();
        jPanelContentDetalle = new javax.swing.JPanel();
        btnDetalle = new javax.swing.JButton();
        jPanelContentInventario = new javax.swing.JPanel();
        btnInventario = new javax.swing.JButton();
        jPanelMantenimiento = new javax.swing.JPanel();
        jPanelContentRegresar = new javax.swing.JPanel();
        jRegresarM = new javax.swing.JButton();
        jPanelContentOpciones = new javax.swing.JPanel();
        jPanelContentProducto = new javax.swing.JPanel();
        btnProducto = new javax.swing.JButton();
        jPanelContentCategoria = new javax.swing.JPanel();
        btnCategoria = new javax.swing.JButton();
        jPanelContentAlmacen = new javax.swing.JPanel();
        btnAlmacen = new javax.swing.JButton();
        jPanelContentMarca = new javax.swing.JPanel();
        btnMarca = new javax.swing.JButton();
        jPanelInicio = new javax.swing.JPanel();
        jFondo = new javax.swing.JLabel();
        jPanelSistema = new javax.swing.JPanel();
        jPanelContentRegresar2 = new javax.swing.JPanel();
        jRegresarM2 = new javax.swing.JButton();
        jPanelContentOpciones2 = new javax.swing.JPanel();
        jPanelContentUsuario = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        jPanelContentRol = new javax.swing.JPanel();
        btnRol = new javax.swing.JButton();
        jPanelContentCliente = new javax.swing.JPanel();
        btnCliente = new javax.swing.JButton();
        jPanelContentProveedor = new javax.swing.JPanel();
        btnProveedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(130, 312));

        jLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSistema.setBackground(new java.awt.Color(153, 153, 153));
        btnSistema.setFont(new java.awt.Font("Julius Sans One", 0, 14)); // NOI18N
        btnSistema.setText("Sistema");
        btnSistema.setBorder(null);
        btnSistema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSistemaMouseClicked(evt);
            }
        });
        btnSistema.addActionListener(this::btnSistemaActionPerformed);

        btnMantenimiento.setBackground(new java.awt.Color(153, 153, 153));
        btnMantenimiento.setFont(new java.awt.Font("Julius Sans One", 0, 14)); // NOI18N
        btnMantenimiento.setText("Mantenimiento");
        btnMantenimiento.setBorder(null);
        btnMantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMantenimientoMouseClicked(evt);
            }
        });

        btnConsultas.setBackground(new java.awt.Color(153, 153, 153));
        btnConsultas.setFont(new java.awt.Font("Julius Sans One", 0, 14)); // NOI18N
        btnConsultas.setText("Consultas");
        btnConsultas.setBorder(null);
        btnConsultas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultasMouseClicked(evt);
            }
        });
        btnConsultas.addActionListener(this::btnConsultasActionPerformed);

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addComponent(jLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        jPanelContent.setBackground(new java.awt.Color(102, 153, 255));

        jPanelConsultas.setBackground(new java.awt.Color(255, 255, 255));

        jPanelContentRegresar1.setBackground(new java.awt.Color(0, 102, 153));

        jRegresarM1.setBackground(new java.awt.Color(102, 102, 102));
        jRegresarM1.setText("Regresar");
        jRegresarM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegresarM1MouseClicked(evt);
            }
        });
        jRegresarM1.addActionListener(this::jRegresarM1ActionPerformed);

        javax.swing.GroupLayout jPanelContentRegresar1Layout = new javax.swing.GroupLayout(jPanelContentRegresar1);
        jPanelContentRegresar1.setLayout(jPanelContentRegresar1Layout);
        jPanelContentRegresar1Layout.setHorizontalGroup(
            jPanelContentRegresar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentRegresar1Layout.createSequentialGroup()
                .addContainerGap(407, Short.MAX_VALUE)
                .addComponent(jRegresarM1)
                .addGap(14, 14, 14))
        );
        jPanelContentRegresar1Layout.setVerticalGroup(
            jPanelContentRegresar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentRegresar1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jRegresarM1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanelContentOpciones1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContentOpciones1.setLayout(new java.awt.GridLayout(2, 2));

        jPanelContenMovimiento.setBackground(new java.awt.Color(255, 255, 255));

        btnMovimiento.setBackground(new java.awt.Color(102, 102, 102));
        btnMovimiento.setText("Movimiento");
        btnMovimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMovimiento.addActionListener(this::btnMovimientoActionPerformed);

        javax.swing.GroupLayout jPanelContenMovimientoLayout = new javax.swing.GroupLayout(jPanelContenMovimiento);
        jPanelContenMovimiento.setLayout(jPanelContenMovimientoLayout);
        jPanelContenMovimientoLayout.setHorizontalGroup(
            jPanelContenMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenMovimientoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelContenMovimientoLayout.setVerticalGroup(
            jPanelContenMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenMovimientoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanelContentOpciones1.add(jPanelContenMovimiento);

        jPanelContentDetalle.setBackground(new java.awt.Color(255, 255, 255));

        btnDetalle.setBackground(new java.awt.Color(102, 102, 102));
        btnDetalle.setText("Detalle");
        btnDetalle.setBorder(null);
        btnDetalle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDetalle.addActionListener(this::btnDetalleActionPerformed);

        javax.swing.GroupLayout jPanelContentDetalleLayout = new javax.swing.GroupLayout(jPanelContentDetalle);
        jPanelContentDetalle.setLayout(jPanelContentDetalleLayout);
        jPanelContentDetalleLayout.setHorizontalGroup(
            jPanelContentDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentDetalleLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelContentDetalleLayout.setVerticalGroup(
            jPanelContentDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentDetalleLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanelContentOpciones1.add(jPanelContentDetalle);

        jPanelContentInventario.setBackground(new java.awt.Color(255, 255, 255));

        btnInventario.setBackground(new java.awt.Color(102, 102, 102));
        btnInventario.setText("Inventario");
        btnInventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInventario.addActionListener(this::btnInventarioActionPerformed);

        javax.swing.GroupLayout jPanelContentInventarioLayout = new javax.swing.GroupLayout(jPanelContentInventario);
        jPanelContentInventario.setLayout(jPanelContentInventarioLayout);
        jPanelContentInventarioLayout.setHorizontalGroup(
            jPanelContentInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentInventarioLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelContentInventarioLayout.setVerticalGroup(
            jPanelContentInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentInventarioLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanelContentOpciones1.add(jPanelContentInventario);

        javax.swing.GroupLayout jPanelConsultasLayout = new javax.swing.GroupLayout(jPanelConsultas);
        jPanelConsultas.setLayout(jPanelConsultasLayout);
        jPanelConsultasLayout.setHorizontalGroup(
            jPanelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContentRegresar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelContentOpciones1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConsultasLayout.setVerticalGroup(
            jPanelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultasLayout.createSequentialGroup()
                .addGap(0, 482, Short.MAX_VALUE)
                .addComponent(jPanelContentRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultasLayout.createSequentialGroup()
                    .addComponent(jPanelContentOpciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 99, Short.MAX_VALUE)))
        );

        jPanelMantenimiento.setBackground(new java.awt.Color(255, 255, 255));

        jPanelContentRegresar.setBackground(new java.awt.Color(0, 102, 153));

        jRegresarM.setBackground(new java.awt.Color(102, 102, 102));
        jRegresarM.setText("Regresar");
        jRegresarM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegresarMMouseClicked(evt);
            }
        });
        jRegresarM.addActionListener(this::jRegresarMActionPerformed);

        javax.swing.GroupLayout jPanelContentRegresarLayout = new javax.swing.GroupLayout(jPanelContentRegresar);
        jPanelContentRegresar.setLayout(jPanelContentRegresarLayout);
        jPanelContentRegresarLayout.setHorizontalGroup(
            jPanelContentRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentRegresarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRegresarM)
                .addGap(14, 14, 14))
        );
        jPanelContentRegresarLayout.setVerticalGroup(
            jPanelContentRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentRegresarLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jRegresarM, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanelContentOpciones.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContentOpciones.setLayout(new java.awt.GridLayout(2, 2));

        jPanelContentProducto.setBackground(new java.awt.Color(255, 255, 255));

        btnProducto.setBackground(new java.awt.Color(102, 102, 102));
        btnProducto.setText("Producto");
        btnProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProducto.addActionListener(this::btnProductoActionPerformed);

        javax.swing.GroupLayout jPanelContentProductoLayout = new javax.swing.GroupLayout(jPanelContentProducto);
        jPanelContentProducto.setLayout(jPanelContentProductoLayout);
        jPanelContentProductoLayout.setHorizontalGroup(
            jPanelContentProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentProductoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelContentProductoLayout.setVerticalGroup(
            jPanelContentProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentProductoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanelContentOpciones.add(jPanelContentProducto);

        jPanelContentCategoria.setBackground(new java.awt.Color(255, 255, 255));

        btnCategoria.setBackground(new java.awt.Color(102, 102, 102));
        btnCategoria.setText("Categoria");
        btnCategoria.setBorder(null);
        btnCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCategoria.addActionListener(this::btnCategoriaActionPerformed);

        javax.swing.GroupLayout jPanelContentCategoriaLayout = new javax.swing.GroupLayout(jPanelContentCategoria);
        jPanelContentCategoria.setLayout(jPanelContentCategoriaLayout);
        jPanelContentCategoriaLayout.setHorizontalGroup(
            jPanelContentCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentCategoriaLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelContentCategoriaLayout.setVerticalGroup(
            jPanelContentCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentCategoriaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanelContentOpciones.add(jPanelContentCategoria);

        jPanelContentAlmacen.setBackground(new java.awt.Color(255, 255, 255));

        btnAlmacen.setBackground(new java.awt.Color(102, 102, 102));
        btnAlmacen.setText("Almacen");
        btnAlmacen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlmacen.addActionListener(this::btnAlmacenActionPerformed);

        javax.swing.GroupLayout jPanelContentAlmacenLayout = new javax.swing.GroupLayout(jPanelContentAlmacen);
        jPanelContentAlmacen.setLayout(jPanelContentAlmacenLayout);
        jPanelContentAlmacenLayout.setHorizontalGroup(
            jPanelContentAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentAlmacenLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelContentAlmacenLayout.setVerticalGroup(
            jPanelContentAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentAlmacenLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanelContentOpciones.add(jPanelContentAlmacen);

        jPanelContentMarca.setBackground(new java.awt.Color(255, 255, 255));

        btnMarca.setBackground(new java.awt.Color(102, 102, 102));
        btnMarca.setText("Marca");
        btnMarca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMarca.addActionListener(this::btnMarcaActionPerformed);

        javax.swing.GroupLayout jPanelContentMarcaLayout = new javax.swing.GroupLayout(jPanelContentMarca);
        jPanelContentMarca.setLayout(jPanelContentMarcaLayout);
        jPanelContentMarcaLayout.setHorizontalGroup(
            jPanelContentMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentMarcaLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelContentMarcaLayout.setVerticalGroup(
            jPanelContentMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentMarcaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanelContentOpciones.add(jPanelContentMarca);

        javax.swing.GroupLayout jPanelMantenimientoLayout = new javax.swing.GroupLayout(jPanelMantenimiento);
        jPanelMantenimiento.setLayout(jPanelMantenimientoLayout);
        jPanelMantenimientoLayout.setHorizontalGroup(
            jPanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContentRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelContentOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMantenimientoLayout.setVerticalGroup(
            jPanelMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMantenimientoLayout.createSequentialGroup()
                .addComponent(jPanelContentOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContentRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelInicio.setBackground(new java.awt.Color(0, 153, 204));

        jFondo.setFont(new java.awt.Font("Julius Sans One", 0, 24)); // NOI18N
        jFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelSistema.setBackground(new java.awt.Color(255, 255, 255));

        jPanelContentRegresar2.setBackground(new java.awt.Color(0, 102, 153));

        jRegresarM2.setBackground(new java.awt.Color(102, 102, 102));
        jRegresarM2.setText("Regresar");
        jRegresarM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegresarM2MouseClicked(evt);
            }
        });
        jRegresarM2.addActionListener(this::jRegresarM2ActionPerformed);

        javax.swing.GroupLayout jPanelContentRegresar2Layout = new javax.swing.GroupLayout(jPanelContentRegresar2);
        jPanelContentRegresar2.setLayout(jPanelContentRegresar2Layout);
        jPanelContentRegresar2Layout.setHorizontalGroup(
            jPanelContentRegresar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentRegresar2Layout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addComponent(jRegresarM2)
                .addGap(14, 14, 14))
        );
        jPanelContentRegresar2Layout.setVerticalGroup(
            jPanelContentRegresar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentRegresar2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jRegresarM2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanelContentOpciones2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContentOpciones2.setLayout(new java.awt.GridLayout(2, 2));

        jPanelContentUsuario.setBackground(new java.awt.Color(255, 255, 255));

        btnUsuario.setBackground(new java.awt.Color(102, 102, 102));
        btnUsuario.setText("Usuario");
        btnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuario.addActionListener(this::btnUsuarioActionPerformed);

        javax.swing.GroupLayout jPanelContentUsuarioLayout = new javax.swing.GroupLayout(jPanelContentUsuario);
        jPanelContentUsuario.setLayout(jPanelContentUsuarioLayout);
        jPanelContentUsuarioLayout.setHorizontalGroup(
            jPanelContentUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentUsuarioLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelContentUsuarioLayout.setVerticalGroup(
            jPanelContentUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentUsuarioLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanelContentOpciones2.add(jPanelContentUsuario);

        jPanelContentRol.setBackground(new java.awt.Color(255, 255, 255));

        btnRol.setBackground(new java.awt.Color(102, 102, 102));
        btnRol.setText("Rol");
        btnRol.setBorder(null);
        btnRol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRol.addActionListener(this::btnRolActionPerformed);

        javax.swing.GroupLayout jPanelContentRolLayout = new javax.swing.GroupLayout(jPanelContentRol);
        jPanelContentRol.setLayout(jPanelContentRolLayout);
        jPanelContentRolLayout.setHorizontalGroup(
            jPanelContentRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentRolLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnRol, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelContentRolLayout.setVerticalGroup(
            jPanelContentRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentRolLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnRol, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanelContentOpciones2.add(jPanelContentRol);

        jPanelContentCliente.setBackground(new java.awt.Color(255, 255, 255));

        btnCliente.setBackground(new java.awt.Color(102, 102, 102));
        btnCliente.setText("Cliente");
        btnCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCliente.addActionListener(this::btnClienteActionPerformed);

        javax.swing.GroupLayout jPanelContentClienteLayout = new javax.swing.GroupLayout(jPanelContentCliente);
        jPanelContentCliente.setLayout(jPanelContentClienteLayout);
        jPanelContentClienteLayout.setHorizontalGroup(
            jPanelContentClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentClienteLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelContentClienteLayout.setVerticalGroup(
            jPanelContentClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentClienteLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanelContentOpciones2.add(jPanelContentCliente);

        jPanelContentProveedor.setBackground(new java.awt.Color(255, 255, 255));

        btnProveedor.setBackground(new java.awt.Color(102, 102, 102));
        btnProveedor.setText("Proveedor");
        btnProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProveedor.addActionListener(this::btnProveedorActionPerformed);

        javax.swing.GroupLayout jPanelContentProveedorLayout = new javax.swing.GroupLayout(jPanelContentProveedor);
        jPanelContentProveedor.setLayout(jPanelContentProveedorLayout);
        jPanelContentProveedorLayout.setHorizontalGroup(
            jPanelContentProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentProveedorLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelContentProveedorLayout.setVerticalGroup(
            jPanelContentProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentProveedorLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanelContentOpciones2.add(jPanelContentProveedor);

        javax.swing.GroupLayout jPanelSistemaLayout = new javax.swing.GroupLayout(jPanelSistema);
        jPanelSistema.setLayout(jPanelSistemaLayout);
        jPanelSistemaLayout.setHorizontalGroup(
            jPanelSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContentRegresar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelContentOpciones2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSistemaLayout.setVerticalGroup(
            jPanelSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSistemaLayout.createSequentialGroup()
                .addGap(0, 482, Short.MAX_VALUE)
                .addComponent(jPanelContentRegresar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSistemaLayout.createSequentialGroup()
                    .addComponent(jPanelContentOpciones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 102, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelConsultas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelSistema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelMantenimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelConsultas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
            .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSistemaActionPerformed

    private void btnSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSistemaMouseClicked
        // TODO add your handling code here:
        //btnSistema.setBackground(new Color(153, 153, 153));
        btnSistema.setBackground(Color.white);
        btnMantenimiento.setBackground(new Color(153, 153, 153));
        btnConsultas.setBackground(new Color(153, 153, 153));
        jPanelSistema.setVisible(true);
        jPanelMantenimiento.setVisible(false);
        jPanelInicio.setVisible(false);
        jPanelConsultas.setVisible(false);

    }//GEN-LAST:event_btnSistemaMouseClicked

    private void btnMantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMantenimientoMouseClicked
        // TODO add your handling code here:
        btnMantenimiento.setBackground(Color.white);
        btnSistema.setBackground(new Color(153, 153, 153));
        btnConsultas.setBackground(new Color(153, 153, 153));
        jPanelSistema.setVisible(false);
        jPanelMantenimiento.setVisible(true);
        jPanelInicio.setVisible(false);
        jPanelConsultas.setVisible(false);
    }//GEN-LAST:event_btnMantenimientoMouseClicked

    private void btnConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultasMouseClicked
        // TODO add your handling code here:
        btnConsultas.setBackground(Color.white);
        btnSistema.setBackground(new Color(153, 153, 153));
        btnMantenimiento.setBackground(new Color(153, 153, 153));
        jPanelSistema.setVisible(false);
        jPanelMantenimiento.setVisible(false);
        jPanelInicio.setVisible(false);
        jPanelConsultas.setVisible(true);
    }//GEN-LAST:event_btnConsultasMouseClicked

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        frmCategoria cat = new frmCategoria();
        cat.setVisible(true);
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void btnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        frmMarca marca = new frmMarca();
        marca.setVisible(true);
        
    }//GEN-LAST:event_btnMarcaActionPerformed

    private void btnAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        frmAlmacen almacen = new frmAlmacen();
        almacen.setVisible(true);
    }//GEN-LAST:event_btnAlmacenActionPerformed

    private void jRegresarMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegresarMMouseClicked
        // TODO add your handling code here:
        jPanelSistema.setVisible(false);
        jPanelMantenimiento.setVisible(false);
        jPanelInicio.setVisible(true);
        jPanelConsultas.setVisible(false);
        
        btnMantenimiento.setBackground(new Color(153, 153, 153));
        btnSistema.setBackground(new Color(153, 153, 153));
        btnConsultas.setBackground(new Color(153, 153, 153));
        
    }//GEN-LAST:event_jRegresarMMouseClicked

    private void jRegresarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegresarMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegresarMActionPerformed

    private void jRegresarM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegresarM1MouseClicked
        // TODO add your handling code here:
        jPanelSistema.setVisible(false);
        jPanelMantenimiento.setVisible(false);
        jPanelInicio.setVisible(true);
        jPanelConsultas.setVisible(false);
        
        btnMantenimiento.setBackground(new Color(153, 153, 153));
        btnSistema.setBackground(new Color(153, 153, 153));
        btnConsultas.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_jRegresarM1MouseClicked

    private void jRegresarM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegresarM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegresarM1ActionPerformed

    private void jRegresarM2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegresarM2MouseClicked
        // TODO add your handling code here:
        jPanelSistema.setVisible(false);
        jPanelMantenimiento.setVisible(false);
        jPanelInicio.setVisible(true);
        jPanelConsultas.setVisible(false);
        
        btnMantenimiento.setBackground(new Color(153, 153, 153));
        btnSistema.setBackground(new Color(153, 153, 153));
        btnConsultas.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_jRegresarM2MouseClicked

    private void jRegresarM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegresarM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegresarM2ActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRolActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        frmRol rol = new frmRol();
        rol.setVisible(true);
        
    }//GEN-LAST:event_btnRolActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        frmCliente cliente = new frmCliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        frmProveedor prove = new frmProveedor();
        prove.setVisible(true);
        
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMovimientoActionPerformed

    private void btnDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalleActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlmacen;
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnDetalle;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnMantenimiento;
    private javax.swing.JButton btnMarca;
    private javax.swing.JButton btnMovimiento;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnRol;
    private javax.swing.JButton btnSistema;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jFondo;
    private javax.swing.JLabel jLogo;
    private javax.swing.JPanel jPanelConsultas;
    private javax.swing.JPanel jPanelContenMovimiento;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelContentAlmacen;
    private javax.swing.JPanel jPanelContentCategoria;
    private javax.swing.JPanel jPanelContentCliente;
    private javax.swing.JPanel jPanelContentDetalle;
    private javax.swing.JPanel jPanelContentInventario;
    private javax.swing.JPanel jPanelContentMarca;
    private javax.swing.JPanel jPanelContentOpciones;
    private javax.swing.JPanel jPanelContentOpciones1;
    private javax.swing.JPanel jPanelContentOpciones2;
    private javax.swing.JPanel jPanelContentProducto;
    private javax.swing.JPanel jPanelContentProveedor;
    private javax.swing.JPanel jPanelContentRegresar;
    private javax.swing.JPanel jPanelContentRegresar1;
    private javax.swing.JPanel jPanelContentRegresar2;
    private javax.swing.JPanel jPanelContentRol;
    private javax.swing.JPanel jPanelContentUsuario;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelMantenimiento;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelSistema;
    private javax.swing.JButton jRegresarM;
    private javax.swing.JButton jRegresarM1;
    private javax.swing.JButton jRegresarM2;
    // End of variables declaration//GEN-END:variables
}
