
package Vista;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;


public class Lista extends PanelRedondeado {

    String path = "";
    String text = "";
    Color backgroundColor = new Color(243,243,243);
    Color backgroundColorHover = new Color(230,230,230);
    
        
    public Lista() {
        initComponents();
        setArc(8);
        setOpaque(false);
        addMouseListener(new MouseAdapter(){
            @Override
            public void mouseEntered(MouseEvent e){
                setBackground(backgroundColorHover);
            }
            
            @Override
            public void mouseExited(MouseEvent e){
                setBackground(backgroundColor);
            }
        
        });
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
        icon.setPath(path);
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
        lblOption.setText(text);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new Vista.ImagenAdaptable();
        lblOption = new javax.swing.JLabel();

        setLayout(null);

        icon.setPath("/Recursos/guardar.png");
        add(icon);
        icon.setBounds(20, 10, 20, 20);

        lblOption.setText("INICIO");
        add(lblOption);
        lblOption.setBounds(50, 10, 170, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.ImagenAdaptable icon;
    private javax.swing.JLabel lblOption;
    // End of variables declaration//GEN-END:variables
}
